/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Mostrar extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    private int renglon = -1;
    private String codigoencontrado = ""; //Varibale para poder encontrara el codigo

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        try {
            initComponents();
            setClosable(true); //Agregamos un boton cerrar
            setDefaultCloseOperation(DISPOSE_ON_CLOSE); //Cerrar mejor que this.hide();

            String[] titulos = {"codigo", "nombre", "correo", "telefono", "edad"};
            modelo = new DefaultTableModel(null, titulos);
            Tabla.setModel(modelo);
            CargarArchivo();
        } catch (IOException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CargarArchivo() throws IOException {
        BufferedReader leer = null;
        try {
            leer = new BufferedReader(new FileReader("agenda.txt"));
            String renglon = "";
            String aux = "";
            while ((renglon = leer.readLine()) != null) {
                String[] datos = renglon.split(" _ ");
                String c = datos[0];
                String n = datos[1];
                String co = datos[2];
                String t = datos[3];
                String e = datos[4];
                modelo.addRow(new Object[]{c, n, co, t, e});
                Tabla.setModel(modelo);
            }
            leer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JButton();
        txtModificar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        txtEliminar.setText("Eliminar");
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(txtEliminar);

        txtModificar.setText("Modificar");
        txtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarActionPerformed(evt);
            }
        });
        jPanel1.add(txtModificar);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(394, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TablaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel4.add(jScrollPane1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(394, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_TablaMouseExited

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked

    }//GEN-LAST:event_TablaMouseClicked

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed
        // TODO add your handling code here:
        if (renglon == -1) {
            JOptionPane.showMessageDialog(null, "Eligir una fila");
        } else {
            FileWriter archivo = null;
            try {
                BufferedReader leer = null;
                archivo = new FileWriter("auxiliar.txt");
                JOptionPane.showMessageDialog(null, codigoencontrado);
                leer = new BufferedReader(new FileReader("agenda.txt"));
                String renglon = "";
                String aux = "";
                while ((renglon = leer.readLine()) != null) {
                    // aux += renglon + "\n";
                    if (renglon.length() != 0) {
                        String[] partes = renglon.split(" _ ");
                        if (codigoencontrado.equals(partes[0])) {
                            String co = JOptionPane.showInputDialog("Escribe el codigo");
                            String nom = JOptionPane.showInputDialog("Escribe el nombre");
                            String cor = JOptionPane.showInputDialog("Escribe el correo");
                            String tel = JOptionPane.showInputDialog("Escribe el telefono");
                            String ed = JOptionPane.showInputDialog("Escribe la edad");
                            nom = nom.toUpperCase();//Pasamos el nombre a mayusculas 
                            cor = cor.toLowerCase(); //Pasamos el correo a misculas 
                            archivo.write(co + " _ " + nom + " _ " + cor + " _ " + tel + " _ " + ed + "\n");
                        } else {
                            //JOptionPane.showMessageDialog(null, partes[0]);
                            archivo.write(renglon + "\n");
                        }
                    }
                }
                archivo.close();

                leer.close();

                File arg = new File("agenda.txt");
                File arg2 = new File("auxiliar.txt");
                Path original = Paths.get("auxiliar.txt");
                Path modificar = Paths.get("agenda.txt");

                if (arg.exists() && arg2.exists()) {
                    Files.move(original, modificar, StandardCopyOption.REPLACE_EXISTING);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtModificarActionPerformed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed
        // TODO add your handling code here:
        renglon = Tabla.getSelectedRow();
        //JOptionPane.showMessageDialog(null, renglon);
        if (renglon == -1) { //si el renglon es -1, se infica que no he precionado ningun elemento de la tabla 
            JOptionPane.showMessageDialog(null, renglon);
        } else { // si lo precione me da el elemeto
            Tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() { //metodo astracto
                @Override
                public void valueChanged(ListSelectionEvent arg0) {
                    JOptionPane.showMessageDialog(null, "Codigo: " + codigoencontrado);
                    codigoencontrado = Tabla.getValueAt(renglon, 0).toString();//Igualar las variables ala columna 0 se la opcion seletcion
                }
            });
        }
    }//GEN-LAST:event_TablaMousePressed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        // TODO add your handling code here:
        if (renglon == -1) {
            JOptionPane.showMessageDialog(null, "Eligue una fila");
        } else {
            BufferedReader leer = null;
            try {
                FileWriter archivo = new FileWriter("auxiliar.txt");
                JOptionPane.showMessageDialog(null, codigoencontrado);
                leer = new BufferedReader(new FileReader("agenda.txt"));
                String renglon = "";
                String aux = "";
                while ((renglon = leer.readLine()) != null) {
                    // aux += renglon + "\n";
                    if (renglon.length() != 0) {
                        String[] partes = renglon.split(" _ ");
                        if (codigoencontrado.equals(partes[0])) {

                        } else {
                            //JOptionPane.showMessageDialog(null, partes[0]);
                            archivo.write(renglon + "\n");
                        }
                    }
                }
                archivo.close();

                leer.close();

                File arg = new File("agenda.txt");
                File arg2 = new File("auxiliar.txt");
                Path original = Paths.get("auxiliar.txt");
                Path modificar = Paths.get("agenda.txt");
                if (arg.exists() && arg2.exists()) {
                    //arg.delete();
                    Files.move(original, modificar, StandardCopyOption.REPLACE_EXISTING);
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    leer.close();
                } catch (IOException ex) {
                    Logger.getLogger(Mostrar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_txtEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton txtEliminar;
    private javax.swing.JButton txtModificar;
    // End of variables declaration//GEN-END:variables
}
