/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clase;

import javax.swing.JOptionPane;

/**
 *
 * @author Diego Plascencia
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUnidades = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cbxCategorias = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cbxCarnes = new javax.swing.JComboBox<>();
        cbxAbarrotes = new javax.swing.JComboBox<>();
        cbxCarnesFrias = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        cbxDecuentos = new javax.swing.JComboBox<>();
        cbxIva = new javax.swing.JComboBox<>();
        cbxUnidades = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAAgregar = new javax.swing.JMenuItem();
        mnmAComprar = new javax.swing.JMenuItem();
        mnuASalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel1.setText("Tipo de producto");
        jPanel11.add(jLabel1);

        lblTipo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblTipo);

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Descripción del producto");
        jPanel11.add(jLabel2);

        lblDescripcion.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblDescripcion);

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setText("Descuentos / Unidades");
        jPanel11.add(jLabel3);

        lblUnidades.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblUnidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblUnidades);

        jPanel1.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(4, 2));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:   ");
        jPanel12.add(jLabel5);

        txtPrecio.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecio.setEnabled(false);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel12.add(txtPrecio);

        jLabel7.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Unidades o peso:   ");
        jPanel12.add(jLabel7);

        txtPeso.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPeso.setEnabled(false);
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        jPanel12.add(txtPeso);

        jLabel6.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sub total:   ");
        jPanel12.add(jLabel6);

        lblSubtotal.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lblSubtotal);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel19);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel16);

        jPanel1.add(jPanel12);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(414, 150));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9);

        cbxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eligue un producto", "Carnes", "Abarrotes", "Carnes frias" }));
        cbxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriasActionPerformed(evt);
            }
        });
        jPanel6.add(cbxCategorias);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10);

        jPanel2.add(jPanel6);

        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        cbxCarnes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eligue un producto", "Res", "Puerco", "Pollo", "Pescado", " " }));
        cbxCarnes.setEnabled(false);
        jPanel8.add(cbxCarnes);

        cbxAbarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eligue un producto", "Azucar", "Sal", "Arina", "Huevo", " " }));
        cbxAbarrotes.setEnabled(false);
        jPanel8.add(cbxAbarrotes);

        cbxCarnesFrias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eligue un producto", "Jamon", "Salchicha", "Queso de puerco", "Chuleta ", " " }));
        cbxCarnesFrias.setEnabled(false);
        jPanel8.add(cbxCarnesFrias);

        jPanel2.add(jPanel8);

        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        cbxDecuentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%" }));
        cbxDecuentos.setEnabled(false);
        jPanel7.add(cbxDecuentos);

        cbxIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12%", "16%", "20%" }));
        cbxIva.setEnabled(false);
        jPanel7.add(cbxIva);

        cbxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieza", "Kilos", "Gramos" }));
        cbxUnidades.setEnabled(false);
        jPanel7.add(cbxUnidades);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel13);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Abarrotes \"Los muertos S.A de C.V\"");
        jPanel3.add(jLabel4);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(50, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("Archirvo");

        mnuAAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAAgregar.setText("Agregar");
        mnuAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAAgregar);

        mnmAComprar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnmAComprar.setText("Comprar ");
        mnmAComprar.setEnabled(false);
        mnmAComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmAComprarActionPerformed(evt);
            }
        });
        jMenu1.add(mnmAComprar);

        mnuASalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuASalir.setForeground(new java.awt.Color(255, 51, 51));
        mnuASalir.setText("Salir");
        mnuASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuASalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuASalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriasActionPerformed
        // TODO add your handling code here:
        if (cbxCategorias.getSelectedItem() == "Eligue un producto") {
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(false);
            cbxDecuentos.setEnabled(false);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem() == "Carnes") {
            cbxCarnes.setEnabled(true);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(false);
            cbxDecuentos.setEnabled(true);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem() == "Abarrotes") {
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(true);
            cbxCarnesFrias.setEnabled(false);
            cbxDecuentos.setEnabled(false);
            cbxIva.setEnabled(true);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem() == "Carnes frias") {
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(true);
            cbxDecuentos.setEnabled(false);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(true);
        }
    }//GEN-LAST:event_cbxCategoriasActionPerformed

    private void mnuAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAAgregarActionPerformed
        // TODO add your handling code here:
        if (cbxCategorias.getSelectedItem() == "Eligue un producto") {
            JOptionPane.showMessageDialog(null, "Elige una opcion de la categoria");
        } else {
            if (cbxCategorias.getSelectedItem() == "Carnes") {
                String tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(tipo);
                String carnes = (String) cbxCarnes.getSelectedItem();
                lblDescripcion.setText(carnes);
                String descuentos = (String) cbxDecuentos.getSelectedItem();
                lblUnidades.setText(descuentos);
                mnuAAgregar.setEnabled(false);
                mnmAComprar.setEnabled(true);
                txtPrecio.setEnabled(true);
            }
            if (cbxCategorias.getSelectedItem() == "Abarrotes") {
                String tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(tipo);
                String aborrotes = (String) cbxAbarrotes.getSelectedItem();
                lblDescripcion.setText(aborrotes);
                String iva = (String) cbxIva.getSelectedItem();
                lblUnidades.setText(iva);
                mnuAAgregar.setEnabled(false);
                mnmAComprar.setEnabled(true);
                txtPrecio.setEnabled(true);
            }
            if (cbxCategorias.getSelectedItem() == "Carnes frias") {
                String tipo = (String) cbxCarnesFrias.getSelectedItem();
                lblTipo.setText(tipo);
                String carnes_frias = (String) cbxCarnesFrias.getSelectedItem();
                lblDescripcion.setText(carnes_frias);
                String unidades = (String) cbxUnidades.getSelectedItem();
                lblUnidades.setText(unidades);
                mnuAAgregar.setEnabled(false);
                mnmAComprar.setEnabled(true);
                txtPrecio.setEnabled(true);
                txtPeso.setEnabled(true);
            }
        }
    }//GEN-LAST:event_mnuAAgregarActionPerformed

    private void mnmAComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmAComprarActionPerformed
        // TODO add your handling code here:
        if (txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Escribe el precio del producto");
        } else {
            if (cbxCategorias.getSelectedItem() == "Carnes") {
                int precio = Integer.parseInt(txtPrecio.getText());
                String de = (String) cbxDecuentos.getSelectedItem();
                de = de.substring(0, de.length() - 1);
                float st = precio - (precio * (Float.parseFloat(de) / 100));
                lblSubtotal.setText(Float.toString(st));
            }
            if (cbxCategorias.getSelectedItem() == "Abarrotes") {
                int precio = Integer.parseInt(txtPrecio.getText());
                String de = (String) cbxIva.getSelectedItem();
                de = de.substring(0, de.length() - 1);
                float st = precio + (precio * (Float.parseFloat(de) / 100));
                lblSubtotal.setText(Float.toString(st));
            }
            if (cbxCategorias.getSelectedItem() == "Carnes frias") {
                if (txtPeso.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Agrega una cantidad o peso del producto");
                } else {
                    int precio = Integer.parseInt(txtPrecio.getText());
                    String de = (String) cbxUnidades.getSelectedItem();
                    de = de.substring(0, de.length() - 1);
                    float peso = Float.parseFloat(txtPeso.getText());
                    float st = precio * peso;
                    lblSubtotal.setText(Float.toString(st));
                }
            }
        }
    }//GEN-LAST:event_mnmAComprarActionPerformed

    private void mnuASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuASalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuASalirActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() >= 48 && evt.getKeyChar() <= 58
                || (evt.getKeyChar() == 8)) {

        } else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten numeros");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() >= 48 && evt.getKeyChar() <= 58
                || (evt.getKeyChar() == 8)) {

        } else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten numeros");
        }
    }//GEN-LAST:event_txtPesoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAbarrotes;
    private javax.swing.JComboBox<String> cbxCarnes;
    private javax.swing.JComboBox<String> cbxCarnesFrias;
    private javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JComboBox<String> cbxDecuentos;
    private javax.swing.JComboBox<String> cbxIva;
    private javax.swing.JComboBox<String> cbxUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JMenuItem mnmAComprar;
    private javax.swing.JMenuItem mnuAAgregar;
    private javax.swing.JMenuItem mnuASalir;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
